### ISSUE TITLE
[Enhancement] Add option to force use24hFormat in showCupertinoTimePicker

### ISSUE THREAD

**Issue by sargntpi** [philip-soft/cupertino_calendar_picker#11]
First of all, thank you so much for building this picker, it's awesome!

I have an app where I allow users to select durations up to a day in length. Using the same time picker but without the AM/PM would allow this to double as a duration picker in certain circumstances.

I'll be raising a PR for this, but happy for it to be left if there are issues/it isn't deemed needed.

**Comment by philip-soft** [comment]
Got it. Okay, this is going to be useful.

Thanks for your kind words and for the contribution!
