### ISSUE TITLE
Localized picker is showing month names instead of weekdays

### ISSUE THREAD

**Issue by ervindobri** [philip-soft/cupertino_calendar_picker#14]
**Current behaviour:**
![image](https://github.com/user-attachments/assets/b70aafd9-99fd-413e-b936-a5cb14d50609)

**Expected behavior:**
- Calendar picker should display weekdays normally for other languages too.

**Steps to reproduce:**
- Change app language to hungarian.
- Observe calendar picker weekdays

investigation suggests that the logic for parsing the weekdays is wrong.
Using localization.datePickerMediumDate(date) in some languages can return the date in a different format, first showing the month instead of the weekday. In our use-case the hungarian format is in the following order: Month, day, weekday

This function should be refactored to use the weekday from the date, not the substring of the medium date.
```
  List<Widget> _weekdays(BuildContext context) {
    assert(debugCheckHasCupertinoLocalizations(context));
    assert(debugCheckHasMaterialLocalizations(context));

    final DateTime nowDate = DateTime.now();
    final int year = nowDate.year;
    final int month = nowDate.month;
    final int firstDayOffset = DateUtils.firstDayOffset(
      year,
      month,
      MaterialLocalizations.of(context),
    );
    final CupertinoLocalizations localization =
        CupertinoLocalizations.of(context);
    final DateTime firstDayOfWeekDate = DateTime(year, month).subtract(
      Duration(days: firstDayOffset),
    );
    return List<Widget>.generate(DateTime.daysPerWeek, (int index) {
      final DateTime date = firstDayOfWeekDate.addDays(index);
      final String mediumDateString = localization.datePickerMediumDate(date);
      final String weekday = mediumDateString.substring(0, 3);

      return Expanded(
        child: CalendarWeekday(
          weekday: weekday.toUpperCase(),
          decoration: decoration,
        ),
      );
    });
  }
```

**Comment by philip-soft** [comment]
Thank you for finding the issue. Starting from version 2.1.0, the intl package will be used.
