### ISSUE TITLE
Xcode Error Building iOS: The getter 'a' isn't defined for the class 'Color'

### ISSUE THREAD

**Issue by danielshuk** [philip-soft/cupertino_calendar_picker#16]
I am getting this Error when building for iOS

`Error (Xcode): ../../.pub-cache/hosted/pub.dev/cupertino_calendar_picker-2.1.0/lib/src/picker/container/picker_container_decoration.dart:37:21: Error: The getter 'a' isn't defined for the class 'Color'.`

I think `color.alpha` is what was intended

**Comment by Likhachev17** [comment]
+1

**Comment by klondikedragon** [comment]
I hit this too. `color.a` was added in flutter 3.27. Use version `2.0.1` of the package until upgrading flutter.

**Comment by danielshuk** [comment]
Ohhh okay. Thanks a lot.

I will close this issue with this as the solution

> I hit this too. `color.a` was added in flutter 3.27. Use version `2.0.1` of the package until upgrading flutter.

**Comment by philip-soft** [comment]
I've just released a new [version](https://github.com/philip-soft/cupertino_calendar_picker/releases/tag/v2.1.1) which brings `a` getter back to maintain compatibility.
