### ISSUE TITLE
Error: Assertions on currentDateTime

### ISSUE THREAD

**Issue by danielshuk** [philip-soft/cupertino_calendar_picker#19]
`'package:cupertino_calendar_picker/src/calendar/picker/cupertino_calendar_picker.dart': Failed assertion: line 32 pos 16: '!currentDateTime.isBefore(minimumDateTime)': is not true.`

I get this error  if today's date doesn't fall within my minimum and maximumDateTime

`currentDateTime` should represent and display today's date unlike `initialDateTime` which represent the initial of the picker. 

I believe `currentDateTime` should have no assertions and will only highlight the date on the calendar whether or not it falls within it's set date range.

**Comment by philip-soft** [comment]
Yes, you're right. Thanks, I will fix it.
