### ISSUE TITLE
Closing the popup after picking a date

### ISSUE THREAD

**Issue by JCKodel** [philip-soft/cupertino_calendar_picker#3]
Wonderful component, but, I'm struggling with the disposing of the popup:

After picking the date, the popup remains on screen.

Using `Navigator.of(context).pop()` makes it disappear instantly (instead of the nice animation we get on clicking outside of it).

How would be the appropriate way of closing the popup after a date has being selected?

And also, wouldn't better to return a `Future<DateTime?>` where the result is `null` for dismissed or a `DateTime` with the selected date?

**Comment by JCKodel** [comment]
The solution for this is on CupertinoCalendarOverlay:

```dart
...
child: CupertinoCalendar(
  onInitialized: _onInitialized,
  weekdayDecoration: widget.weekdayDecoration,
  monthPickerDecoration: widget.monthPickerDecoration,
  containerDecoration: widget.containerDecoration,
  headerDecoration: widget.headerDecoration,
  minimumDate: widget.minimumDate,
  initialDate: widget.initialDate,
  currentDate: widget.currentDate,
  maximumDate: widget.maximumDate,
  onDateChanged: (value) {
    if(widget.onDateChanged != null) {
      widget.onDateChanged(value);
      _onOutsideTap();
    }
  },
  onDisplayedMonthChanged: widget.onDisplayedMonthChanged,
  scaleAlignment: scaleAligment,
  maxScale: maxScale,
  mainColor: widget.mainColor,
),
...
```

Also, in the same component, the `Stack` (root child of `build` method) should be wrapped on a `PopScope`, otherwise, the Android back button will dismiss the popup without the animation, so:

```dart
...
return PopScope(
  canPop: false,
  onPopInvoked: (_) => _onOutsideTap(),
  child: Stack(
    clipBehavior: Clip.none,
    children: <Widget>[
      Positioned.fill(
        child: GestureDetector(
          onTap: _onOutsideTap,
          behavior: HitTestBehavior.translucent,
          child: const ColoredBox(color: Colors.transparent),
        ),
      ),
...
```

**Comment by philip-soft** [comment]
Thank you for the feedback, @JCKodel. I will add these changes in the next release.

**Comment by philip-soft** [comment]
The [v1.1.2](https://pub.dev/packages/cupertino_calendar_picker/versions/1.1.2) version has been released with the described changes. 

Thanks again, and let me know if you have anything else to share.

**Comment by JCKodel** [comment]
Awesome!
